---
- name: Restart systemd-journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted
  when: not ansible_check_mode

- name: Skip systemd-journald restart in check mode
  ansible.builtin.debug:
    msg: "Check mode enabled, skipping systemd-journald restart."
  when: ansible_check_mode
