# This is inventory file for production stage

[ubuntu]
docker1 ansible_host=docker1.kirby.lan
docker2 ansible_host=docker2.kirby.lan
pi1 ansible_host=pi1.kirby.lan

[pi]
pi2 ansible_host=pi2.kirby.lan
pi3 ansible_host=pi3.kirby.lan

[all:vars]
# Sets the environment to development(dev) or production (prod) or test
environment=prod


[docker_servers]
docker1 ansible_host=10.27.70.11 docker_tls_san_ips='["10.27.70.11","127.0.0.1"]'

[docker_clients]
docker2 ansible_host=10.27.70.12
docker3 ansible_host=10.27.70.13
docker4 ansible_host=10.27.70.14

[all:vars]
ansible_user=koerbcm
