---
timezone: Etc/UTC
base_hostname_manage: false
base_hostname: "{{ inventory_hostname }}"
base_hostname_aliases: []
base_apt_force_ipv4: false
base_apt_cache_valid_time: 3600
base_apt_lock_timeout: 300
base_apt_normalize_ubuntu_archive_mirror: true
base_apt_ubuntu_archive_mirror: http://archive.ubuntu.com/ubuntu
base_apt_ubuntu_archive_mirror_aliases:
  - http://us.archive.ubuntu.com/ubuntu
base_packages: []
base_groups: []
base_additional_groups: []
base_users: []
base_extra_users: []
base_additional_users: []
base_user_password_hashes: {}
base_break_glass_users: []
base_require_break_glass_passwords: false
base_auto_remove_unused_gid_conflict_groups: true
base_groups_ignore_gid_for:
  - docker
base_group_gid_migrations: []
base_users_ignore_uid_for: []
base_skip_uid_for_connected_user: true
base_auto_omit_conflicting_user_uids: true
base_fail_on_user_uid_conflicts: false
