---
docker_prerequisite_packages:
  - ca-certificates
  - curl
  - gnupg

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_apt_arch_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf
  armv6l: armhf

docker_admin_users: []
docker_dns_servers: []
docker_gelf_address: ""
docker_daemon_hosts:
  - "unix:///var/run/docker.sock"
docker_tls_enabled: false
docker_tls_verify: false
docker_tls_san_ips: []
docker_tls_subject_alt_names: []
docker_cert_valid_days: 3650
