---
all:
  vars:
    ansible_user: koerbcm
  children:
    homelab:
      hosts:
        docker1:
          ansible_host: docker1.kirby.lan
        docker2:
          ansible_host: docker2.kirby.lan
        pi1:
          ansible_host: pi1.kirby.lan
        pi2:
          ansible_host: pi2.kirby.lan
        pi4:
          ansible_host: pi4.kirby.lan
    maintenance_hosts:
      hosts:
        docker1:
        docker2:
        pi1:
        pi2:
        pi4:
    ubuntu_hosts:
      hosts:
        docker1:
        docker2:
        pi1:
        pi2:
    raspberry_pi_os_hosts:
      hosts:
        pi4:
    docker_hosts:
      hosts:
        docker1:
        docker2:
        pi1:
        pi2:
        pi4:
    nfs_clients:
      hosts:
        docker1:
        docker2:
        pi1:
        pi2:
        pi4:
    identity_clients:
      hosts:
        docker1:
        docker2:
        pi1:
        pi2:
        pi4:
    legacy_cleanup_hosts:
      hosts:
        pi2:
    log_forwarder_hosts:
      hosts:
        docker1:
        pi1:
    ntfy_hosts:
      hosts:
        pi2:
    uptime_kuma_hosts:
      hosts:
        pi4:
    uptime_kuma_backup_hosts:
      hosts:
        pi4:
    radarr_hosts:
      hosts:
        pi1:
    sonarr_hosts:
      hosts:
        pi1:
    sabnzbd_hosts:
      hosts:
        pi1:
    lazylibrarian_hosts:
      hosts:
        pi1:
    app_config_backup_hosts:
      hosts:
        pi1:
    plex_hosts:
      hosts:
        docker2:
    plex_backup_hosts:
      hosts:
        docker2:
    postgresql_hosts:
      hosts:
        docker2:
    postgresql_backup_hosts:
      hosts:
        docker2:
    netdata_hosts:
      hosts:
        docker1:
        docker2:
        pi1:
        pi2:
        pi4:
    homepage_hosts:
      hosts:
        docker1:
    ombi_hosts:
      hosts:
        docker1:
    it_tools_hosts:
      hosts:
        docker1:
    n8n_hosts:
      hosts:
        docker2:
    n8n_backup_hosts:
      hosts:
        docker2:
    invoice_ninja_hosts:
      hosts:
        docker2:
    invoice_ninja_backup_hosts:
      hosts:
        docker2:
    portainer_hosts:
      hosts:
        docker1:
    nextcloud_hosts:
      hosts:
        docker1:
    paperless_hosts:
      hosts:
        docker1:
    mysql_hosts:
      hosts:
        docker1:
    mysql_backup_hosts:
      hosts:
        docker1:
    watchtower_hosts:
      hosts:
        pi1:
        docker2:
    portainer_agent_hosts:
      hosts:
        docker2:
        pi1:
        pi2:
    graylog_hosts:
      hosts:
        docker1:
    graylog_backup_hosts:
      hosts:
        docker1:
    docker_tls_servers:
      hosts:
        docker1:
