---
- name: Reload rsyslog AppArmor profile
  ansible.builtin.command:
    cmd: apparmor_parser -r /etc/apparmor.d/usr.sbin.rsyslogd
  when: not ansible_check_mode

- name: Restart rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted
  when: not ansible_check_mode

- name: Skip rsyslog restart in check mode
  ansible.builtin.debug:
    msg: "Check mode enabled, skipping rsyslog restart."
  when: ansible_check_mode
